apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: testwebapp
  namespace: team1
spec:
  interval: 1m
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: testwebapp
    namespace: team1
